FROM golang:latest

WORKDIR /app
ADD ./src /app

RUN go install -mod=mod github.com/githubnemo/CompileDaemon
RUN go get github.com/gin-gonic/gin

ENTRYPOINT CompileDaemon --build="go build -o /main main.go" --command=/main